# Use postgres/example user/password credentials
version: '3.7'

services:

    db:
     image: postgres:12-alpine
     restart: always
     ports:
      - '5432'
     environment:
      POSTGRES_PASSWORD: 12345

    adminer:
      image: adminer
      restart: always
      ports:
        - "8080:9999"